Extract DevelopmentMailInterceptor setup from config/environment/
NZOI/nztrain pull request #198
Opened 2023-12-21 08:20 UTC by bagedevimo

This makes rails upgrades easier, as it means the diff between the
template-added is near-zero. There's no reason not to set this up here,
we just have to be a little careful about rails load order (use
Mail#register_interceptor instead of ActionMailer).

2023-12-21 08:20 UTC, bagedevimo commented
Current dependencies on/for this PR:
* `master`
  * **PR #198** <a href="https://app.graphite.dev/github/pr/NZOI/nztrain/198?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/NZOI/nztrain/198?utm_source=stack-comment).

2023-12-21 09:39 UTC, tom93 requested changes
Is this missing the removal from config/environments/development.rb?

2023-12-21 09:47 UTC, bagedevimo commented
> Is this missing the removal from config/environments/development.rb?

Yes, lol. Fixed now.

2023-12-22 06:15 UTC, tom93 approved these changes

2023-12-22 06:33 UTC, merged